<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="*" />
  </ItemGroup>
</Project>
