using System.Text.Json.Serialization;

namespace PhotoPrism.Sdk;

/// <summary>
/// Internal record implementation of IPhotoSearchResult.
/// </summary>
internal record PhotoSearchResult(
    [property: JsonPropertyName("UID")] string? UID = default,
    [property: JsonPropertyName("ID")] string? ID = default,
    [property: JsonPropertyName("Title")] string? Title = default,
    [property: JsonPropertyName("Caption")] string? Caption = default,
    [property: JsonPropertyName("Description")] string? Description = default,
    [property: JsonPropertyName("OriginalName")] string? OriginalName = default,
    [property: JsonPropertyName("Name")] string? Name = default,
    [property: JsonPropertyName("Path")] string? Path = default,
    [property: JsonPropertyName("Type")] string? Type = default,
    [property: JsonPropertyName("TypeSrc")] string? TypeSrc = default,
    [property: JsonPropertyName("TakenAt")] DateTime? TakenAt = default,
    [property: JsonPropertyName("TakenAtLocal")] DateTime? TakenAtLocal = default,
    [property: JsonPropertyName("TakenSrc")] string? TakenSrc = default,
    [property: JsonPropertyName("TimeZone")] string? TimeZone = default,
    [property: JsonPropertyName("Year")] int Year = default,
    [property: JsonPropertyName("Month")] int Month = default,
    [property: JsonPropertyName("Day")] int Day = default,
    [property: JsonPropertyName("Lat")] double? Lat = default,
    [property: JsonPropertyName("Lng")] double? Lng = default,
    [property: JsonPropertyName("Altitude")] int Altitude = default,
    [property: JsonPropertyName("Country")] string? Country = default,
    [property: JsonPropertyName("PlaceID")] string? PlaceID = default,
    [property: JsonPropertyName("PlaceSrc")] string? PlaceSrc = default,
    [property: JsonPropertyName("CellID")] string? CellID = default,
    [property: JsonPropertyName("CellAccuracy")] int CellAccuracy = default,
    [property: JsonPropertyName("CameraID")] int CameraID = default,
    [property: JsonPropertyName("CameraMake")] string? CameraMake = default,
    [property: JsonPropertyName("CameraModel")] string? CameraModel = default,
    [property: JsonPropertyName("CameraSerial")] string? CameraSerial = default,
    [property: JsonPropertyName("CameraSrc")] string? CameraSrc = default,
    [property: JsonPropertyName("CameraType")] string? CameraType = default,
    [property: JsonPropertyName("LensID")] int LensID = default,
    [property: JsonPropertyName("LensMake")] string? LensMake = default,
    [property: JsonPropertyName("LensModel")] string? LensModel = default,
    [property: JsonPropertyName("FocalLength")] int FocalLength = default,
    [property: JsonPropertyName("FNumber")] float FNumber = default,
    [property: JsonPropertyName("Iso")] int Iso = default,
    [property: JsonPropertyName("Exposure")] string? Exposure = default,
    [property: JsonPropertyName("Quality")] int Quality = default,
    [property: JsonPropertyName("Resolution")] int Resolution = default,
    [property: JsonPropertyName("Color")] int Color = default,
    [property: JsonPropertyName("Duration")] TimeSpan? Duration = default,
    [property: JsonPropertyName("Faces")] int Faces = default,
    [property: JsonPropertyName("Favorite")] bool Favorite = default,
    [property: JsonPropertyName("Private")] bool Private = default,
    [property: JsonPropertyName("Scan")] bool Scan = default,
    [property: JsonPropertyName("Panorama")] bool Panorama = default,
    [property: JsonPropertyName("Portrait")] bool Portrait = default,
    [property: JsonPropertyName("Stack")] int Stack = default,
    [property: JsonPropertyName("DocumentID")] string? DocumentID = default,
    [property: JsonPropertyName("InstanceID")] string? InstanceID = default,
    [property: JsonPropertyName("Hash")] string? Hash = default,
    [property: JsonPropertyName("Width")] int Width = default,
    [property: JsonPropertyName("Height")] int Height = default,
    [property: JsonPropertyName("FileUID")] string? FileUID = default,
    [property: JsonPropertyName("FileName")] string? FileName = default,
    [property: JsonPropertyName("FileRoot")] string? FileRoot = default,
    [property: JsonPropertyName("Merged")] bool Merged = default,
    [property: JsonPropertyName("PlaceCity")] string? PlaceCity = default,
    [property: JsonPropertyName("PlaceState")] string? PlaceState = default,
    [property: JsonPropertyName("PlaceCountry")] string? PlaceCountry = default,
    [property: JsonPropertyName("PlaceLabel")] string? PlaceLabel = default,
    [property: JsonPropertyName("DetailsArtist")] string? DetailsArtist = default,
    [property: JsonPropertyName("DetailsCopyright")] string? DetailsCopyright = default,
    [property: JsonPropertyName("DetailsKeywords")] string? DetailsKeywords = default,
    [property: JsonPropertyName("DetailsLicense")] string? DetailsLicense = default,
    [property: JsonPropertyName("DetailsSubject")] string? DetailsSubject = default,
    [property: JsonPropertyName("CreatedAt")] DateTime? CreatedAt = default,
    [property: JsonPropertyName("UpdatedAt")] DateTime? UpdatedAt = default,
    [property: JsonPropertyName("DeletedAt")] DateTime? DeletedAt = default,
    [property: JsonPropertyName("EditedAt")] DateTime? EditedAt = default,
    [property: JsonPropertyName("CheckedAt")] DateTime? CheckedAt = default,
    [property: JsonPropertyName("Files")] IReadOnlyList<File>? Files = default
) : IPhotoSearchResult
{
    IReadOnlyList<IFile>? IPhotoSearchResult.Files => Files?.Cast<IFile>().ToList();
}
